### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by aforren1** [aforren1/replan_finger#1]
- [x] Feedback for timing
- [x] Ensure all (relevant) data is saved
- [x] Save truncated, easy-to-digest data separately
- [x] Visual feedback for press/no press? YES -- put bar below stimulus/fix cross
- [x] Handle no-press case (hang until any press, see finger-6)
